NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
> png('plot1.png')
> TotalEmissionsPerYear <- aggregate(Emissions ~ year, NEI, sum)
> barplot(height=TotalEmissionsPerYear$Emissions, names.arg = TotalEmissionsPerYear$year, xlab = "years", ylab = "Emissions")
> dev.off()
